### PR TITLE
Use Tuple Swap and SwitchExpression and fix spelling errors in 3 files

### PR DESCRIPTION
**Pull request by paul1956**
Flag two issues with comments that need to be reviewed

### CODE REVIEW

**Comment by kirsan31** [comment]
Pls remove `switch statement to switch expression` refactoring. `Switch expression` is  a _bit_ slower, and we don't want any slowdown in charts...
Also replay [here](https://github.com/kirsan31/winforms-datavisualization/issues/4#issuecomment-1298513793) pls.

**Comment by paul1956** [comment]
I think I reverted all switch changes, added editor.config to project to stop suguesting it.
Fixed lots of spelling errors.

**Comment by kirsan31** [comment]
@paul1956 

> According to CyrusNajmabadi switch expressions are the same codegen as switch statements. Identical performance.

I've checked - you are right. Performance of switch expression +- the same as switch statement now days. 50000 iteration with switch on string:
Snipaste_2022-11-06_12-27-36

Those. I think we can safely use it if it gives somehow an explicit code reduction. Sorry for confusing your first time.

About others part of the PR:

> added editor.config to project to stop suggesting it

We already [have one](https://github.com/kirsan31/winforms-datavisualization/blob/dev/.editorconfig). Also `IDE0066` as we found out above, is probably not necessary to exclude.

And again 
image

is too much to review in one time :(

**Comment by paul1956** [comment]
Only 4 files have code changes, the rest are spelling mistakes, there are over 5,000 spelling issues (only comments are charged). Would you prefer I delete this PR and start over?

**Comment by kirsan31** [comment]
> Only 4 files have code changes, the rest are spelling mistakes, there are over 5,000 spelling issues (only comments are charged). Would you prefer I delete this PR and start over?

I see a modified file - I have to check it :(

You no need to open a new PR, you can to modify you current local branch as your want (to leave not much changes) and then do a **force** push (to override remote PR branch).

**Comment by paul1956** [comment]
With with 5000+ spelling issues including many identical, it will take a lot of PR. Some words are spelled wrong in dozens of files.

Would you prefer I change 1 file at a time per PR? If so I can just start over since most of the work is automated. Except some comment cleanup which I now understand I need to do.

**Pull request closed without merging**
